title: Sharwari Phadnis
name: Sharwari
email: sharwariphadnis@gmail.com
description: "Hello! Welcome to my Portfolio!"
baseurl: "/blog"
url: "https://sharwari09.github.io"

display_footer: inital  #change this to 'none' if you want to hide the footer copyright text

parallax_image_one: assets/images/startup3.jpg # These are the images used for the parallax background
parallax_image_two: assets/images/startup3.jpg

project_one: "BookMyEvent"
project_one_description: "BookMyEvent is an event creation and ticketing app. It allows users to browse, create, local and far events. There are 4 microservices that cater to different features such as user registration, creating an event, booking an event, and a dashboard service that displays created and booked events for an organizer or a regular user. This app is completely containerized has been deployed on Microsoft Azure Kubernetes Service. MongoDb, and Riak KV have been used as the Database backend for the app."
project_one_url: https://github.com/sharwari09/sp19-281-mavericks
project_one_icon: location_on

project_two: "Prototype of Federated Byzantine Algorithm"
project_two_description: "The project uses FBA protocol to enable data replication on various nodes in a cluster. Implemented a key-value datastore service that persists user wallet info: username and balance. If a user does not exist in DB, the service will create a new entry with a given value. Otherwise, the user wallet will be updated with the new amount. For node to node communication, Twisted UDP protocol has been used. PickleDB has been is used for storing the FBA protocol messages."
project_two_url: https://github.com/jameshamann/jekyll-material-theme
project_two_icon: photo_camera


project_three: Data Sharding Techniques
project_three_description: "Implemented different techniques such as Consistent Hashing and Rendezvous Hashing for data sharding work by building a RESTful key-value datastore API and hashing client. Python Flask has been used to build the API service."
project_three_url: "https://github.com/sharwari09/Distributed-Systems/tree/master/Data-Sharding"
project_three_icon: hotel


project_four: GRPC-Chat-Messenger
project_four_description: "Build a Chat Messenger using GRPC in Python3. Have used gRPC response streaming to continuously receive chat messages from the Chat server. Designed one-on-one conversations between users. Implemented a LRU Cache to store recent messages in memory. Limited the number of messages a user can send to an API within a time window. Provided end-to-end message encryption using AES from PyCrypto library. Also, supports group chats."
project_four_url: https://github.com/sharwari09/Distributed-Systems/tree/master/GRPC-Chat-Messenger
project_four_icon: restaurant

portfolio_heading: Portfolio
portfolio_type: cards

syntax_highlighting: true
# Skill icons from https://konpa.github.io/devicon/

skills:
  - name: amazonwebservices
  - name: ansible
  - name: airflow
  - name: apache
  - name: apple
  - name: atom
  - name: bitbucket
  - name: bootstrap
  - name: c
  - name: confluence
  - name: debian
  - name: django
  - name: docker
  - name: git
  - name: github
  - name: gitlab
  - name: go
  - name: google
  - name: gradle
  - name: heroku
  - name: html5
  - name: itellij
  - name: java
  - name: javascript
  - name: linux
  - name: mongodb
  - name: mysql
  - name: nginx
  - name: oracle
  - name: postgresql
  - name: python
  - name: pycharm
  - name: redhat
  - name: redis
  - name: slack
  - name: ssh
  - name: tomcat
  - name: travis
  - name: ubuntu
  - name: vim
  - name: visualstudio
  - name: wordpress


icon_size: 50 # font-size of icons in px
colored: colored # Leave blank for black and white icons

project_button: Github

github: https://github.com/sharwari09
linkedin: https://www.linkedin.com/in/sharwari-phadnis/

baseurl: # if your site is located at /blog or /home, enter it here, otherwise leave it empty
url: http://localhost:4000/ #the url of your site

# Google tracking, if both are filled, tag manager will prevail. Set up GA through GTM in that case
tag_manager_id: # This looks something like GTM-XXXXXXX
google_analytics_tracking_id: # This looks something like UA-000000000-0 Head over to https://analytics.google.com/ to setup.

cookies_banner: show # The value "show" will show the cookies banner, the value "none" will hide the banner.

cookie_accept_message: Thanks!

syntax_highlighting: true # include the css for syntax highlighting

# Build settings
markdown: kramdown
# theme: minima
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-minifier
